### ISSUE TITLE
Speed display incorrect

### ISSUE THREAD

**Issue by ThatPlasma** [mikigal/Anime4K-GUI#10]
The Speed thing shows as 0.5 speed (this is the speed of the CPU upscaling while the normal full GPU shows it as 1x speed

noted last night in the testing for an unknown reason when using the CPU encoding it breaks the speed

**Comment by mikigal** [comment]
What's speed with enabled `Compatibility mode` and what's your hardware?
On my setup (i7-12700KF + RTX 3070) I have very similar speed with CPU and GPU encoding.
I'm also working now with feature that allow you to select manually encoder (H264, H265, AV1, GPU and CPU based) so I will back to this issue after new release

**Comment by ThatPlasma** [comment]
ohh AV1 encoding and using CUDA+NVENC my speed was 1x, Using CPU+H.264 my speed was 0.5x, Using CUDA+H.264 shows my speed as 0.5 but actually upscales it at 1x

**Comment by ThatPlasma** [comment]
oh hardware Ryzen 7 2700 and a GTX 1060 6gb

**Comment by mikigal** [comment]
With RTX 1060 you couldn't use `av1_nvenc`. It require RTX 4000 series GPU.
Value in speed indicator in GUI is simple passed from FFMPEG logs so I'm not sure what can I do about it.
Please manually measure speed ratio (input length:upscaling time)

**Comment by ThatPlasma** [comment]
oh i have manually measured it thats why I know CUDA+H.264 is 1x

and what about AV1 CPU encoding?

**Comment by mikigal** [comment]
For me:
1. AV1 - 4x speed  (50% CPU usage, 20% GPU usage)
2. H265 - 1.4x speed (100% CPU usage, 30% GPU usage)
3. H264 - 3.7x speed (70-100% CPU, 35% GPU usage), for example with NVENC i get 4.3x here

**Comment by ThatPlasma** [comment]
i see well i have a slower system

**Comment by mikigal** [comment]
Please add me on Discord (Miyukki) or Telegram (t.me/mikigal) if you want to test beta version of next release with manually selecting encoders

**Comment by ThatPlasma** [comment]
done

**Comment by mikigal** [comment]
I didn't get any invite. Please give me your Discord name/Telegram link

**Comment by ThatPlasma** [comment]
discord thatplasma

**Comment by ThatPlasma** [comment]
i dont have telegram

**Comment by mikigal** [comment]
Fixed in latest commits
