### ISSUE TITLE
Can add option change preset and crf for cpu ?

### ISSUE THREAD

**Issue by iamzuika** [mikigal/Anime4K-GUI#12]
Ex:  -preset medium -crf 18

**Comment by Pixellevel** [comment]
Can you add the option to directly set the bitrate? Because I found that even with the default, even the low options, the output file is still much smaller than the original file. It's compressed too much. Can we set it ourselves?

**Comment by mikigal** [comment]
Hi, I already implemented it and it will be released soon

**Comment by mikigal** [comment]
Implemented in https://github.com/mikigal/Anime4K-GUI/commit/fa44f9d48c50a0ba17e34adedfbf2a8199b983da
