### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by joskezelensky** [mikigal/Anime4K-GUI#19]
how to use ffmpeg from path for this program?
do i need to build it from source when those paths have changed or will you be providing a new "feature"

**Comment by mikigal** [comment]
Hi,
there's no way to use ffmpeg from PATH variable.
You can replace ffmpeg binary in `ffmpeg` directory in app folder

**Comment by mikigal** [comment]
You can try with symlink, if it not work simply copy your ffmpeg.exe and paste it into ffmpeg directory of application

**Comment by joskezelensky** [comment]
> You can try with symlink, if it not work simply copy your ffmpeg.exe and paste it into ffmpeg directory of application

okidoki
