### ISSUE TITLE
1.1.5 High DPI scale issue

### ISSUE THREAD

**Issue by Kevin-2106** [mikigal/Anime4K-GUI#23]
Running on Windows 11 23H2.
My display is 2560x1600 with a DPI scale of 150%. Running the program would cause itself infinitely scaling larger, outside the screen, resulting in MAX usage of CPU and RAM, then crash.

I believe it was a issue with DPI scale, as when the High DPI scale replacement was set to `system` (System simply Integer scale the application window), it works well.

**Comment by mikigal** [comment]
This issue was caused by Giu bug (https://github.com/AllenDang/giu/pull/812)
I updated Giu to 0.8.1 (https://github.com/mikigal/Anime4K-GUI/commit/e274a7162b0fc83d7efc334ea7e9f61bb411d7ad) and released [v1.1.6](https://github.com/mikigal/Anime4K-GUI/releases/tag/v1.1.6)
