### ISSUE TITLE
Option to choose quality

### ISSUE THREAD

**Issue by AziRizvi** [mikigal/Anime4K-GUI#5]
Can we get an option in the GUI to choose the quality ourselves? What I mean to say is let's say I don't want to use the built-in quality parameters in the GUI and I want to use ffmpeg's crf 0 or crf 52 or whatever, we should be able to do that, maybe perhaps we can also get a input box in the GUI where we can also pass on additional FFmpeg CLI parameters?

Thank you!

**Comment by mikigal** [comment]
Hi,
I didn't know about CFR parameter. Currently I'm only passing preset - https://trac.ffmpeg.org/wiki/Encode/H.264#a2.Chooseapresetandtune

I will add simple input as you suggested with CFR value. 
Manually manipulating FFMPEG's params will require some dialog with table as I have to pass paramter name and it's value as two parameters into function call

**Comment by AziRizvi** [comment]
> Hi, I didn't know about CFR parameter. Currently I'm only passing preset - https://trac.ffmpeg.org/wiki/Encode/H.264#a2.Chooseapresetandtune
> 
> I will add simple input as you suggested with CFR value. I'm not sure how to handle CFR and preset simultaneously. Do you have any idea about it?
> 
> Manually manipulating FFMPEG's params will require some dialog with table as I have to pass paramter name and it's value as two parameters into function call

I'm sorry I don't have any idea about that since I've personally always used ffmpeg just for basic stuff like extracting or merging subtitles and format/container conversion.

**Comment by mikigal** [comment]
I tested some CRF values and didn't notice any changes in output video quality
