### ISSUE TITLE
Keep video's original aspect ratio

### ISSUE THREAD

**Issue by 1412367** [mikigal/Anime4K-GUI#6]
Hi. thank you for this great tool. I have some video that not in 4:3 nor 16:9. How can I keep its aspect ratio/prevent stretch?

**Comment by mikigal** [comment]
You have to select some upscale resolution marked as 4:3

**Comment by 1412367** [comment]
> You have to select some upscale resolution marked as 4:3

You confused me. Select 4:3 would stretch the video vertical or horizontal. That's the problem and I was asking how to prevent that stretch.
So are you saying there's no way to prevent videos that aren't both 4:3 and 16:9 (e.g. 5:3) from being stretched, or you didn't understand my question?

**Comment by mikigal** [comment]
Only 4:3 and 16:9 input resolutions are supported - other will be stretched.
I didn't implement support for other ratios because I never seen series/videos in ratio like 5:3
