### ISSUE TITLE
Option to select video encoder

### ISSUE THREAD

**Issue by ThatPlasma** [mikigal/Anime4K-GUI#8]
i have a 1060 and while with CUDA I can do 1:1 speeds the use of NVENC takes a 200mb into a 30mb low bitrate mess with the Low compression and while I can turn off Hardware A, it takes twice as long to upscale so is there a way to use CUDA to upscale but CPU to encode

**Comment by mikigal** [comment]
Hi,
please check latest release (v1.0.6) - https://github.com/mikigal/Anime4K-GUI/releases/tag/v1.0.6
Make sure to use "Disable GPU encoding acceleration" feature

**Comment by ThatPlasma** [comment]
yeah i know thanks, i got one of my friends to add it in kinda crazy it got officially added so quickly
